### PR TITLE
facerecognizer is broken

### PR DESCRIPTION
**Pull request by randomstring**
The general problem is that there are two separate lib directories:  facerecognition_tester/lib and facetrainer/lib. The new threading code didn't get fully tested in facerecognition_tester. So it was completely broken on the raspberry pi.

This pull request fixes the threading issue (specifically update to lib/config.py to run camera.start())

I added some other changes to make it easier to debug like translating to English and inserting some placeholder usernames in "user = []"

Long term it would be better to unify the two lib/ directories to avoid duplication of code.

### CODE REVIEW

**Comment by paviro** [comment]
Thanks a lot! I agree with you they should be unified.. any chance you could have a look? Not sure when I will have the time to look into it :/

**Comment by randomstring** [comment]
I will look into unifying the two lib directories. I'm planning to do more testing with facerecognition_tester

**Comment by randomstring** [comment]
OK, I think I have it all unified and working. https://github.com/randomstring/MMM-Facial-Recognition-Tools

I fixed some bugs and made some usability improvements along the way. 

I created a TODO.md to track some other issues to make the face recognition and the tool better.

Someone else should test this out (other than just me) and confirm that it still works with the MMM-Facial-Recognition plugin. Which I haven't even got to yet.

**Comment by Patrick-Remy** [comment]
Your fork is working well for me, after adding missing python path! 👍

**Comment by paviro** [comment]
Very nice todo list! 👍  I send you an collaborator invite! :)

**Comment by randomstring** [comment]
Thanks. I've already committed support for opencv version 3. Need to check them off on the todo list. Although I don't have a way to test OpenCV version 3 right now.

The cascade face detection doesn't do very well with glasses. That part comes pre-trained. I've researched enough to learn that you can train your own. However I'm curious to find out where the haarcascade_frontalface.xml came from. Augmenting the original training data would be better than starting from scratch. I also started looking at OpenFace as a possible replacement. Because, you know, neural nets would be cooler.

**Comment by paviro** [comment]
The `haarcascade_frontalface.xml` comes from [here](https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_frontalface_alt.xml). Definitely agree on that :D neural nets would be way cooler :)

**Comment by randomstring** [comment]
@paviro thanks for the link! haarcascade_eye_tree_eyeglasses.xml looks promising. I'm going to experiment with some of these soon. Maybe you could run one or more profile in parallel.

https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_eye_tree_eyeglasses.xml

**Comment by paviro** [comment]
Just don't forget the processing power of the pi! :D

**Comment by randomstring** [comment]
Well using the haarcascade_eye_tree_eyeglasses.xml didn't work out. It's a detector for eyes not faces. I wrote a code that would extrapolate the face from the eye location, but the eye location finder would more often return more or fewer than two eyes. I tried some of the alt face haarcascades, but they were no better than the default that's already there.

My experimentation showed that the biggest problem with face detection with glasses is glare on the lenses obscuring the eyes. 

There's still more in the TODO list, but I'm calling this "done for now."

I made a pull request. It touches almost everything:
 - collapse the two lib dirs into one common lib. 
 - some major pep8 python style cleanup
 - Integrated CV3 support
 - partial cleanup to make python 3 compliant (got stuck on raw_input())
 - merged in other features that popped on the mainline

**Pull request merged**
