### PR TITLE
Use submodule face for opencv3 support

### PR DESCRIPTION
**Pull request by falgard**
I don't have access to an older version of opencv at the moment so not sure if this is backward compatible. However it's needed for opencv3, you might want to add that to your readme or create a new branch for it. Thanks for the repo!

### CODE REVIEW

**Comment by paviro** [comment]
Could you add some lines to check which version of opencv is installed and then execute the right one based on that?

**Comment by falgard** [comment]
Sure, I'll look into it! Just wanted to let you know, definitely don't want to merge it if it breaks something.

**Comment by paviro** [comment]
Just make sure there is a check and I will happily merge it. Thanks a lot for your effort!

**Comment by paviro** [comment]
Any news? :)

**Comment by falgard** [comment]
Sorry for the delay.. I tried it out on another computer with the older version and it worked fine there as well, just forget to get back. Someone else might want to check it out but should work. thanks!

**Comment by randomstring** [comment]
Opencv3 support is merged into the main line now.

**Pull request closed without merging**
