### PR TITLE
Major overhaul

### PR DESCRIPTION
**Pull request by randomstring**
- Merge to one common lib directory
- merged in cv3 support from @falgard
- merged in smaller picam preview from benkej05
- code cleanup: conform to common python style (mostly)
- code cleanup: make the code python3 compatible (with exception of raw_input() calls)
- set username list from ENV, removed need to change .py file to add list of usernames for testing
- move common config code to config.py

I think my work here is done. It's good enough.

### CODE REVIEW

**Comment by paviro** [comment]
Hey there so sorry completely forgot about this... Could you fix the conflicts so I can merge it?

**Comment by randomstring** [comment]
The 3 conflicts are just files that need to be deleted with "git rm"  They are files that got moved to the common /lib directory.

I tried to purge the fix back, but I don't have permission on https://github.com/paviro/MMM-Facial-Recognition-Tools.git/

**Comment by paviro** [comment]
I could not fix it 😅 But you should have permission to push to the repo :/

**Comment by randomstring** [comment]
I think I successfully pushed the merge. Github doesn't seem to support 2-factor authentication from the command line. So I resorted to the GUI.

**Pull request merged**
